### PR TITLE
License agreement popup doesn't show up after 30 days (#2210)

### LINKED ISSUE #2210: License agreement popup doesn't show up after 30 days
### Expected behavior
License expires in 30 days and application shows agreement popup for user to accept it again.

### Actual behavior
License agreement popup doesn't show up after 30 days.

### Steps to reproduce behavior
Check item "terms-and-conditions-acceptance-date" in the localStorage. If it points to a moment not older than 30 days, then alter it (ie 1581187689000 - it is 8 Feb 2020). Check if license agreement shows up.

The problem is here: js/components/terms-and-conditions/terms-and-conditions.js:50
```
const isExpired = momentApi.diffInDays(parseInt(acceptanceDate, 10), momentjs().add(appConfig.termsAndConditions.acceptanceExpiresInDays, 'days')) <= 0;
```
isExpired is always false.

### PR DESCRIPTION
**Pull request by anton-abushkevich**
Fixes #2210

### CODE REVIEW

File: js/components/terms-and-conditions/terms-and-conditions.js [hunk 1]
```diff
@@ -45,7 +43,7 @@ define([
     checkAcceptance() {
       const acceptanceDate = localStorage.getItem('terms-and-conditions-acceptance-date');
       if (acceptanceDate !== null) {
-        const isExpired = momentApi.diffInDays(parseInt(acceptanceDate, 10), momentjs().add(appConfig.termsAndConditions.acceptanceExpiresInDays, 'days')) <= 0;
+        const isExpired = momentApi.diffInDays(parseInt(acceptanceDate), Date.now()) > appConfig.termsAndConditions.acceptanceExpiresInDays;
```
Comment (wivern) [inline js/components/terms-and-conditions/terms-and-conditions.js:46]: But why you removed the radix parameter?
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/parseInt

Comment (anton-abushkevich) [reply js/components/terms-and-conditions/terms-and-conditions.js]: fixed
