### PR TITLE
Removed a call to 'check' endpoint during deleting of cohort definition

### LINKED ISSUE #2172: Deleting a cohort definition calls the 'check' endpoint
### Expected behavior

When deleting a cohort definition, no REST errors are returned.

### Actual behavior

When deleting a cohort definition, the endpoint `/WebAPI/cohortdefinition/<id>/check` is called after the entity is deleted causing an error.

### Steps to reproduce behavior

With chrome developer tools open, delete a cohort and observe the error.

### PR DESCRIPTION
**Pull request by ssuvorov-fls**
fixes #2172

### CODE REVIEW

File: js/pages/cohort-definitions/components/checks/conceptset-warnings.js [hunk 1]
```diff
@@ -91,19 +91,23 @@ define(['knockout', 'text!./conceptset-warnings.html',
       };
 
       self.getWarnings = function() {
-        if (parseInt(self.cohortDefinitionId(), 10) <= 0 || isNaN(self.cohortDefinitionId())) {
-          return false;
+        if (this.cohortDefinitionId()) {
```
Comment (vlbe) [inline js/pages/cohort-definitions/components/checks/conceptset-warnings.js:94]: cohortDefinitionId becomes undefined after you try to save newly created concept so the check will not fire any more after changing the cohort definition

Comment (ssuvorov-fls) [reply js/pages/cohort-definitions/components/checks/conceptset-warnings.js]: fixed
