### PR TITLE
Ir link now opens report, Cohort link now opens report(#1819)

### LINKED ISSUE #1819: Clicking on links in Notification screen should bring user to results that were generated
### Expected behavior

From Notifications screen, clicking on a link would open the analysis on the results section of whatever was generated.

### Actual behavior

Inconsistent referencing from the Notifications screen:

image

Here, the incidence rate link sends to the incidene rate design page.  Characterization goes to the characterization results page (loads the results).   Heracles cohort link goes to cohort reporting, but then user must select source and report.   Cohort goes to cohort/generation page, but not selected on 'view reports' for the cohort generated.   Pathways analysis opens the results for the generated source.

### Steps to reproduce behavior

Click through links of generated features in ATLAS and see how they go to different places.

### PR DESCRIPTION
**Pull request by ssuvorov-fls**
fixes #1819 
Ir link now opens report
Heracles cohort link goes to cohort reporting and selects source
Cohort link now opens report

### CODE REVIEW

File: js/pages/incidence-rates/components/iranalysis/components/results.js [hunk 1]
```diff
@@ -73,15 +73,23 @@ define([
...
+				} else {
+					this.selectSourceBySourceId();
+				}
 			}));
 			this.subscriptions.push(this.selectedOutcome.subscribe((newVal) => {
-				if (this.selectedSource()) // this will cause a report refresh
+				if (this.selectedSource()) {// this will cause a report refresh
 					this.selectSource(this.selectedSource());
+				} else {
+					this.selectSourceBySourceId();
```
Comment (pavgra) [inline js/pages/incidence-rates/components/iranalysis/components/results.js]: Would be better to avoid `if` here and have single path

File: js/pages/cohort-definitions/cohort-definition-manager.js [hunk 2]
```diff
@@ -1213,9 +1214,17 @@ define(['jquery', 'knockout', 'text!./cohort-definition-manager.html',
...
 						results.push(cdsi);
+
+						if (selectedSourceId && source.sourceId === selectedSourceId) {
+							selectedSourceInfo = cdsi;
+						}
 					}
 					this.cohortDefinitionSourceInfo(results);
 
+					if (selectedSourceInfo) {
+						this.toggleCohortReport(selectedSourceInfo);
```
Comment (pavgra) [inline js/pages/cohort-definitions/cohort-definition-manager.js]: image

File: js/pages/incidence-rates/routes.js [hunk 3]
```diff
@@ -13,14 +13,20 @@ define(
           analysisId = parseInt(analysisId);
           path = path.split("/");
           let activeTab = null;
+          let selectedSourceId = null;
           if (path.length > 0 && path[0] !== "") {
             activeTab = path[0];
           }
+          // source_id
+          if (path.length > 1 && path[1] !== "") {
```
[the remark this answers is not in the document]
Comment (ssuvorov-fls) [reply js/pages/incidence-rates/routes.js]: 1. Open IR -> Go to Generation tab -> Click Reports
It opens the page with all reports but does not open concrete report
2. Follow link in Notifications
It opens the page with all reports and then opens concrete report

File: js/pages/incidence-rates/components/iranalysis/components/results.js (hunk 1 above)
Comment (ssuvorov-fls) [reply js/pages/incidence-rates/components/iranalysis/components/results.js]: fixed

File: js/pages/cohort-definitions/cohort-definition-manager.js (hunk 2 above)
Comment (ssuvorov-fls) [reply js/pages/cohort-definitions/cohort-definition-manager.js]: fixed

File: js/pages/incidence-rates/routes.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (YaroslavTir) [reply js/pages/incidence-rates/routes.js:21]: steps:
1) generate IR for to data sources (ds1 and ds2)
2) open report for ds1
3) click notification for ds2
**expected result**
open report for ds2
**actual result**
nothing happened

**Comment by anton-abushkevich** [comment]
### Routing issues

**Cohort generation & heracles cohort report**
URL doesn't change on tab selection in cohort, which leads to various issues.

1. Click heracles report link in Notifications modal
2. Go to another tab (URL remains unchanged)
3. Click heracles report link in Notifications modal again - nothing happens.

Almost the same for cohort generation:
1. Click cohort generation link in Notifications modal
2. Go to another tab (URL remains unchanged)
3. Click cohort generation link in Notifications modal again - nothing happens.

with some additions:
1. Click cohort generation link in Notifications modal when not in cohort - generation tab opens and report for source opens ok 
2. Click heracles report link in Notifications modal for the same cohort - report opens ok
3. Click cohort generation link in Notifications modal again - generation tab opens, but report for source closed. Repeat the steps from 2 and report opens. Repeat again and it's closed.

**Pathways**
Generate 2 reports for 2 sources for the same pathway.
1. Click pathway report link in Notifications modal - opens ok
2. Click second source report link - opens pathway's design page. Further clicks on these 2 links does not work, we stay at design page, although URL changes correspondingly.

**Incidence rates**
Generate 2 reports for 2 sources for the same Incidence Rate.
1. Click Incidence Rate report link in Notifications modal - opens ok.
2. Click second Incidence Rate report link in Notifications modal - nothing happens. Furthermore, if you move to desing tab and click second report link - opens first report.

**Estimations** (confirmed only for failed reports)
Generate 2 reports for 2 sources for the same Estimation.
1. Click Estimation report link in Notifications modal - reports list opens ok.
2. Click second Estimation report link in Notifications modal - nothing happens. Furthermore, if you move to another tab and click either report link for this Estimation - nothing happens.

**Predictions** (confirmed only for failed reports)
Generate 2 reports for 2 sources for the same Prediction.
1. Click Prediction report link in Notifications modal - reports list opens ok.
2. Click second Prediction report link in Notifications modal - reports list for corresponding source opens ok. 
3. Click first Prediction report link again in Notifications modal - nothing happens. 
Furthermore, if you move to another tab and click either report link for this Prediction - nothing happens.

**Comment by ssuvorov-fls** [comment]
@anton-abushkevich fixed according to your notes
