### PR TITLE
fixed execution engine ping

### LINKED ISSUE #703: execution engine checks failed when user not signed in
### Expected behavior
execution engine checks are performed only for authenticated user
### Actual behavior
execution engine checks fail with 401 code

### PR DESCRIPTION
**Pull request by johnSamilin**
fixes #703

### CODE REVIEW

File: js/main.js [hunk 1]
```diff
@@ -253,10 +253,17 @@ requirejs(['bootstrap'], function () { // bootstrap must come first
       }
 		}
 
+		function checkExecutionEngineStatus(isAuthenticated) {
```
Comment (pavgra) [inline js/main.js]: Move to EE related service
