### PR TITLE
Fixed navigation to DS page at Configuration screen

### LINKED ISSUE #794: DS cannot be opened in configuration view
### Expected behavior
DS is opened in configuration view
### Actual behavior
DS cannot be opened in configuration view
### Steps to reproduce behavior
Open DS in configuration view

### PR DESCRIPTION
**Pull request by johnSamilin**
fixes #794

### CODE REVIEW

File: js/app.js [hunk 1]
```diff
@@ -35,10 +35,10 @@ define([
 		var appModel = function () {
 			$.support.cors = true;
 			var self = this;
-			let appRoutes = {};
+			let routes = {};
```
Comment (wivern) [inline js/app.js]: as to me I would make it immutable:
`const routes = self.pages.reduce((r, page) => ({...r, ...page.buildRoutes(self)}), {})`

File: js/pages/configuration/routes.js [hunk 2]
```diff
@@ -31,6 +31,25 @@ define(
...
+          appModel.activePage(this.title);
+          require(['source-manager'], function () {
+            appModel.componentParams = {
+              model: appModel,
+            };
+            appModel.currentView('source-manager');
+          });
+        }),
+        '/source/:id': new AuthorizedRoute((id) => {
+          appModel.activePage(this.title);
```
Comment (wivern) [inline js/pages/configuration/routes.js]: code duplications
