### PR TITLE
Fixed exception in data completeness report

### LINKED ISSUE #1258: Heracles "Data completeness" report throws exception
image

### PR DESCRIPTION
**Pull request by vlbe**
Fixes #1258

### CODE REVIEW

File: js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js [hunk 1]
```diff
@@ -2160,16 +2160,17 @@ define([
 
 				this.currentAgeGroup('Age group of: ' + oneBarData.covariance);
 				svg = d3.select("#dataCompletenessSvgDiv").append("svg");
-				const margin = {
+				svg.attr("width", 960)
+				svg.attr("height", 500)
```
Comment (pavgra) [inline js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js]: What's the reason for re-ordering of margin definition and svg attrs?

File: js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js [hunk 2]
```diff
@@ -2160,16 +2160,17 @@ define([
...
+
+				let margin = {
```
Comment (pavgra) [inline js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js]: Why was it switched from `const` to `let`?
