### PR TITLE
Fix candidate negative control display

### LINKED ISSUE #1888: Negative control link display
### Expected behavior

Links to concepts identified in the negative control process are properly formatted.

### Actual behavior

image

### PR DESCRIPTION
**Pull request by anthonysena**
Updates the negative control table options to use the `render` property where applicable. Updated to centralize formatters to a single function call. Fixes #1888

### CODE REVIEW

File: js/components/evidence/utils.js [hunk 1]
```diff
@@ -12,8 +12,18 @@ define(['knockout'], function(ko){
             row.ancestorSplicerCount > 0
         )
     }
+
+    function formatNumberWithCommas(val) {
+      return val.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
```
Comment (pavgra) [inline js/components/evidence/utils.js]: Don’t we have `numeral` library for this?

Comment (anthonysena) [reply js/components/evidence/utils.js]: Nice catch - I forgot about that library. I'll update to use that instead.
