### PR TITLE
Fixed reloading of the data in Concept Manager

### LINKED ISSUE #1132: Middle section of Vocabulary retains lines from previous click
### Steps to reproduce behavior
a)	Clicked on a concept in a concept set
b)	Viewed hierarchy
c)	Clicked on a parent in the hierarchy
d)	Shows original and parent in middle section

### PR DESCRIPTION
**Pull request by johnSamilin**
fixes #1132

### CODE REVIEW

File: js/pages/concept-sets/concept-manager.js [hunk 1]
```diff
@@ -349,6 +340,13 @@ define([
 			super.onPageCreated();
 		}
 
+		onRouterParamsChanged({ conceptId }) {
+			if (this.model.currentConceptMode() == 'recordcounts') {
+				this.loadRecordCounts();
+			}
+			this.loadConcept(value);
```
Comment (pavgra) [inline js/pages/concept-sets/concept-manager.js]: Where the `value` variable comes from?

image

**Comment by pavgra** [comment]
Seems like requests are duplicated:
image
