### PR TITLE
Fixed endless loader in compare cs table header

### LINKED ISSUE #1474: Compare concept set: endless loader in the table header for RC/DRC
### Expected behavior
When compare concept set, after datasource change DB icon is displayed in the table header for RC/DRC

### Actual behavior
When compare concept set, after datasource change endless loader is displayed in the table header for RC/DRC

test-2 7 0-20190307-cs-compare2

after change DS

test-2 7 0-20190307-cs-compare3

### Steps to reproduce behavior
Open section Concept sets
Choose one of Concept set
Go to Compare tab
Choose Concept set 2 for compare
Press button "Compare Concept set"
DB icon is displayed in the header
Change datasource 
Endless loader is displayed in the header

### PR DESCRIPTION
**Pull request by vlbe**
Fixes #1474

### CODE REVIEW

File: js/pages/concept-sets/components/tabs/conceptset-compare.js [hunk 1]
```diff
@@ -321,39 +321,40 @@ define([
...
+
     showSaveNewModal() {
 			this.saveConceptSetShow(true);
     }
 
     refreshRecordCounts(obj, event) {
 			if (event.originalEvent) {
-				// User changed event
+        // User changed event
+        console.log(this)
```
Comment (pavgra) [inline js/pages/concept-sets/components/tabs/conceptset-compare.js]: why?
