### PR TITLE
Fixed prompt message when closing FA create form

### LINKED ISSUE #1862: Empty feature analysis bug
### Expected behavior

When creating a feature analysis for characterization, I'm prompted to save changes when I've done some work.

### Actual behavior

Attempting to close an empty feature analysis prompts "Your changes are not saved. Would you like to continue?"

### Steps to reproduce behavior

Create a new feature analysis. Then try to close it. You'll get the prompt mentioned above.

### PR DESCRIPTION
**Pull request by vlbe**
Fixes #1862

### CODE REVIEW

File: js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js [hunk 1]
```diff
@@ -202,6 +202,7 @@ define([
         }
 
         setupAnalysisData({ id = 0, name = '', descr = '', domain = '', type = '', design= '', conceptSets = [], statType = 'PREVALENCE' }) {
+            domain = !!domain ? domain : !!this.domains()[0] && !!this.domains()[0].value ? this.domains()[0].value : '';
```
Comment (pavgra) [inline js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js]: This is not readable. Cannot we introduce a couple of variables with seld-descriptive names?

Comment (vlbe) [reply js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js]: Fixed
