### PR TITLE
Fixed missing loaders

### LINKED ISSUE #1329: Loaders are missing
Loaders are missing in the following cases

**Login**
image

**Source creation** (click Save on new Source page):
image

### PR DESCRIPTION
**Pull request by vlbe**
Fixes #1329

### CODE REVIEW

File: js/services/AuthAPI.js [hunk 1]
```diff
@@ -429,7 +429,13 @@ define(function(require, exports) {
 
 	var setAuthParams = function (tokenHeader) {
         token(tokenHeader);
-        loadUserInfo();
+        return new Promise((resolve, reject) => {
```
Comment (pavgra) [inline js/services/AuthAPI.js]: Why do you need to wrap it in the separate promise? Why not just to `return loadUserInfo();`?

Comment (vlbe) [reply js/services/AuthAPI.js]: Yes, it's no need to wrap. I'll fix it.
