### PR TITLE
Fixed remaining modal backdrop

### LINKED ISSUE #1865: Issue with remaining modal backdrop
### Expected behavior
Screen is clickable
### Actual behavior
Screen is not clickable because of modal backdrop
### Steps to reproduce behavior
1) Open Included concepts in cohort definitions
2) Find some with ancestors > 0
3) Click on number (Modal window appears)
4) Click on Concept name

### PR DESCRIPTION
**Pull request by vlbe**
Fixes #1865

This PR depends on https://github.com/OHDSI/Atlas/pull/1852

### CODE REVIEW

File: js/pages/concept-sets/conceptset-manager.js [hunk 1]
```diff
@@ -130,7 +131,10 @@ define([
 				{
 						title: 'Included Concepts',
 						componentName: 'included-conceptsets',
-						componentParams: params,
+						componentParams: {
```
Comment (pavgra) [inline js/pages/concept-sets/conceptset-manager.js]: Same as https://github.com/OHDSI/Atlas/pull/1896#pullrequestreview-248404467

File: js/pages/concept-sets/conceptset-manager.js [hunk 2]
```diff
@@ -176,10 +176,11 @@ define([
 
 		dispose() {
 			this.fade(false); // To close modal immediately, otherwise backdrop will freeze and remain at new page
+			// this.ancestorsModalIsShown(false);
```
Comment (pavgra) [inline js/pages/concept-sets/conceptset-manager.js]: Why?
