### PR TITLE
Fixed Included Concepts is not updated when Descendants checkbox is turned on / off

### LINKED ISSUE #848: Count in Concept set -> Included Concepts is not updated when Descendants checkbox is turned on / off
count-not-updated

### PR DESCRIPTION
**Pull request by wivern**
Fixes #848

### CODE REVIEW

File: js/components/conceptsetInclusionCount/conceptsetInclusionCount.js [hunk 1]
```diff
@@ -23,6 +23,11 @@ define([
 
 			this.getInclusionCount = this.getInclusionCount.bind(this);
 			this.conceptSetExpression.subscribe(this.getInclusionCount);
+			this.conceptSetExpression().forEach((item) => {
+				item.includeDescendants.subscribe(this.getInclusionCount);
+				item.includeMapped.subscribe(this.getInclusionCount);
+				item.isExcluded.subscribe(this.getInclusionCount);
+			});
```
Comment (pavgra) [inline js/components/conceptsetInclusionCount/conceptsetInclusionCount.js]: @wivern , cannot we apply more universal `ko.computed(() => ko.toJSON(root)).subscribe(this.getInclusionCount)` instead of 6 lines above?
