### PR TITLE
Pathway reporting fixes:

### LINKED ISSUE #2365: Unable to export Cohort Pathway legend
### Expected behavior
Should be able to export the legend as a PNG (just like sunburst).

### Actual behavior
Unable to export the HTML legend as an image.

### Steps to reproduce behavior
1. Run a pathway analysis.
2. Observe only an export option is given for the SVG elements (the sunburst)

### PR DESCRIPTION
**Pull request by chrisknoll**
Added export pathway legend function.
Fixed calculation of table reports by removing '-end' markers from pathway results.
New dependency: html2canvas added via NPM.
Renamed ChartUtils function from downloadAsPng to downloadSvgAsPng.

Fixes #2365.

### CODE REVIEW

**Comment by chrisknoll** [comment]
Remember to npm install after pulling this PR, since new dependency: html2canvas has been added.

File: js/pages/pathways/components/tabs/pathway-tableview.js [hunk 1]
```diff
@@ -311,12 +309,21 @@ define([
...
 			
-			const data = Array.from(Array.from(dataMap.values())).concat([{eventCohorts: 0, personCount: (pathwayGroup.cohortCount - pathwayGroup.pathwayCount)}]);
+			const data = Array.from(dataMap.values());
 			
 			data.forEach(row => { // add pathway and cohort percents
 				row.pathwayPercent = 100.0 * row.personCount / pathwayGroup.pathwayCount;
 				row.cohortPercent = 100.0 * row.personCount / pathwayGroup.cohortCount;
 			});
+
+			// add the zedro-case to result
```
Comment (anthonysena) [inline js/pages/pathways/components/tabs/pathway-tableview.js:319]: Small typo: zedro-case

**Review by anthonysena — DISMISSED** [review]
Works well after my testing. Found a small typo in a comment but otherwise good-to-go!

**Review by anthonysena — APPROVED** [review]
