### PR TITLE
fixed exception on charts (bad data)

### LINKED ISSUE #914: Units, Values, Concepts charts shouldn't be empty in Measurement report of Achilles
### Expected behavior
Units, Values, Concepts charts shouldn't be empty in Measurement report of Achilles

### Actual behavior
The charts are empty
image

### Steps to reproduce behavior
1. Go to Data sources
1. Select a source
1. Open Measurement report
1. Click on a concept

### PR DESCRIPTION
**Pull request by johnSamilin**
closes #914 
also need improvements into @ohdsi/atlascharts package

### CODE REVIEW

File: js/modules/databindings/chart.js [hunk 1]
```diff
@@ -20,7 +20,12 @@ define(['knockout'], (ko) => {
   ko.bindingHandlers.chart = {
 		update: function (element, valueAccessor) {
       const chart = valueAccessor();
-			draw(chart.data(), element, chart.minHeight, chart.format, chart.renderer);
+      try {
+        draw(chart.data(), element, chart.minHeight, chart.format, chart.renderer);
+      } catch(er) {
+        console.error('Error when rendering chart');
```
Comment (pavgra) [inline js/modules/databindings/chart.js]: Why wouldn't you add exception object to logger?

Comment (johnSamilin) [reply js/modules/databindings/chart.js]: because first, it tells nothing (it doesn't know anything about chart's name), and second, the actual bug is in the `atlascharts` (it doesn't check data for validity)

**Comment by chrisknoll** [comment]
@johnSamilin : if the atlascharts throws an exception, tho, would it be different?  We can throw exceptions in the charting library, we just haven't yet.
