### PR TITLE
Bypass refreshToken() when authentication is not enabled.

### LINKED ISSUE #2899: Atlas 2.14.0 - Characterization - /user/refresh with 404 when user authentication not enabled
### Expected behavior

In 2.14.0 version of Atlas, can navigate to Characterizations section and browse any of existing characterization from the list displayed. Shall display selected characterization information.

(Likewise, creating New Characterization is problematic in the same way.)

### Actual behavior

Pop-up dialog with message `Error! Please see server logs for details.` and blank page appears.

The culprit seems to be access attempt to /user/refresh endpoint when user authentication for the whole setup is not enabled.

Firefox console:

user-refresh-404-firefox-console

Tomcat access logs, IP redacted:

```
...
192.168.XX.YYY - - [13/Dec/2023:12:30:56 +0000] "GET /WebAPI/cohort-characterization/52/design HTTP/1.1" 200 1146
192.168.XX.YYY - - [13/Dec/2023:12:30:56 +0000] "GET /WebAPI/user/refresh HTTP/1.1" 404 5
192.168.XX.YYY - - [13/Dec/2023:12:31:18 +0000] "GET /WebAPI/notifications?hide_statuses= HTTP/1.1" 200 625
...
```

### Steps to reproduce behavior

In 2.14.0 version of Atlas, navigate to Characterizations section and try to browse any of existing characterization from the list displayed. Problematic behaviour discovered by Marek Oja.

### Possible fix

We used to fix a line in [js/services/AuthAPI.js](https://github.com/OHDSI/Atlas/blob/v2.14.0/js/services/AuthAPI.js#L257) where instead

```
        if (!isPromisePending(refreshTokenPromise)) {
```

we use

```
        if (!isPromisePending(refreshTokenPromise) && (config.userAuthenticationEnabled)) {
```

Works fine for us, for now.

### Related

* https://github.com/OHDSI/Atlas/issues/2820 - UI Laggs when retrieving results from /refresh
* https://github.com/OHDSI/Atlas/pull/2835/files/54f7d6d78797f831b9c0aea9254e10590d481eca# - Reduce polling to /user/refresh #2835

user-refresh-refreshToken-in-loadCharacterizationDesign

### PR DESCRIPTION
**Pull request by chrisknoll**
Fixes #2899

### CODE REVIEW

File: js/services/AuthAPI.js [hunk 1]
```diff
@@ -254,6 +254,10 @@ define(function(require, exports) {
     }
     var refreshToken = function() {
 
+        if (!config.userAuthenticationEnabled) {
+            return Promise.resolve(true); // no-op if userAthenticationEnabmed == false
```
Comment (harry-anton) [inline js/services/AuthAPI.js:258]: Typo in comments: ...Enabmed -> ...Enabled
