### PR TITLE
fixed check of the current state of the generation

### LINKED ISSUE #1014: Generate button does not show activity when status of job is 'STARTING'
Not related to #968.

### Expected behavior
Clicking generate button should show a spinner that there is activity for this source.

### Actual behavior
Clicking generate does kick off a job and marks it as 'STARTING', but does not show a sniper in this state.

### Steps to reproduce behavior
Hard to reproduce, exactly, because it is not clear when a state of an execution is STARTING vs. STARTED. However, to reproduce, keep clicking on generate buttons until you get to the point where the job status is 'STARTING' and you will find the generate button doesn't have the spinner.

### LINKED ISSUE #1128: Generate button on characterization execution page doesn't show generating
### Expected behavior
When generating multiple characterizations for several databases the generate button will show for those datasources generating with moving circle
### Actual behavior
When generating multiple characterizations for several databases the generate button doesn't show for all datasources generating with moving circle
### Steps to reproduce behavior
For a given characterization click generate for 4 databases, watch generate button, some do not change

### PR DESCRIPTION
**Pull request by johnSamilin**
fixes #1128 
also fixes #1014

### CODE REVIEW

File: js/pages/pathways/components/tabs/pathway-executions.js [hunk 1]
```diff
@@ -80,7 +80,7 @@ define([
 					data: 'results',
 					className: this.classes('col-exec-results'),
 					render: (s, p, d) => {
-						return d.status === this.pathwayGenerationStatusOptions.COMPLETED ? `<a data-bind="css: $component.classes('reports-link'), click: $component.goToResults.bind(null, id)">View reports</a>` : '-';
+						return d.status() === this.pathwayGenerationStatusOptions.COMPLETED ? `<a data-bind="css: $component.classes('reports-link'), click: $component.goToResults.bind(null, id)">View reports</a>` : '-';
```
Comment (pavgra) [inline js/pages/pathways/components/tabs/pathway-executions.js]: What about the same change in CC?
