### PR TITLE
Physical dates on Patient profile, as a configurable option 

### LINKED ISSUE #556: Atlas profile - add calendar dates to x-axis in addition to days
### Expected behavior
Display two x-axis. 
One x-axis be number of days from day 0. (current)
Second x-axis be calendar dates

### Actual behavior
Only one axis

### Steps to reproduce behavior
http://www.ohdsi.org/web/atlas/#/profiles/CS1/1

For instances where patient privacy is a concern, add this to role-based access control using Shiro (ability to see dates on person profiles)

### PR DESCRIPTION
**Pull request by wivern**
closes #556

### CODE REVIEW

File: js/components/profile/profile-manager.js [hunk 1]
```diff
@@ -114,6 +110,9 @@ define(['knockout', 'text!./profile-manager.html', 'd3', 'appConfig', 'webapi/Au
 					url: url,
 					method: 'GET',
 					contentType: 'application/json',
+					data: {
```
Comment (pavgra) [inline js/components/profile/profile-manager.js]: Wasn't there a will to replace the call with ProfileAPI.getProfile ?

**Comment by anthonysena** [comment]
Please see comments on https://github.com/OHDSI/WebAPI/pull/378#issuecomment-379959311 and if you have no concerns with my changes, we can merge this into master.

File: js/components/profile/profileChart.js [hunk 2]
```diff
@@ -274,6 +283,13 @@ define(['knockout', 'd3', 'd3-tip', 'lodash', 'd3-selection', 'D3-Labeler/labele
 			.attr("transform", "translate(0," + (vizHeight + 2) + ")")
 			.call(xAxis);
 
+		if (config.viewProfileDates && (!config.userAuthenticationEnabled || (config.userAuthenticationEnabled && authApi.isPermittedViewProfileDates()))) {
```
Comment (pavgra) [inline js/components/profile/profileChart.js]: The condition inside *if* is duplicated - move to separate method
